enum WeatherConditions {
  CLEAR_SKY_DAY = '01d',
  FEW_CLOUDS_DAY = '02d',
  SCATTERED_CLOUDS_DAY = '03d',
  BROKEN_CLOUDS_DAY = '04d',
  SHOWER_RAIN_DAY = '09d',
  RAIN_DAY = '10d',
  THUNDERSTORM_DAY = '11d',
  SNOW_DAY = '13d',
  MIST_DAY = '50d',
  CLEAR_SKY_NIGHT = '01n',
  FEW_CLOUDS_NIGHT = '02n',
  SCATTERED_CLOUDS_NIGHT = '03n',
  BROKEN_CLOUDS_NIGHT = '04n',
  SHOWER_RAIN_NIGHT = '09n',
  RAIN_NIGHT = '10n',
  THUNDERSTORM_NIGHT = '11n',
  SNOW_NIGHT = '13n',
  MIST_NIGHT = '50n',
  ERROR_CLOUD = 'error',
}

export const WEATHER_IMAGES: Record<WeatherConditions, string> = {
  [WeatherConditions.CLEAR_SKY_DAY]: require('../images/clear_sky_day.png'),
  [WeatherConditions.FEW_CLOUDS_DAY]: require('../images/few_clouds.png'),
  [WeatherConditions.SCATTERED_CLOUDS_DAY]: require('../images/scattered_clouds.png'),
  [WeatherConditions.BROKEN_CLOUDS_DAY]: require('../images/broken_clouds.png'),
  [WeatherConditions.SHOWER_RAIN_DAY]: require('../images/shower_rain.png'),
  [WeatherConditions.RAIN_DAY]: require('../images/rain.png'),
  [WeatherConditions.THUNDERSTORM_DAY]: require('../images/thunderstorm.png'),
  [WeatherConditions.SNOW_DAY]: require('../images/snow.png'),
  [WeatherConditions.MIST_DAY]: require('../images/mist.png'),
  [WeatherConditions.CLEAR_SKY_NIGHT]: require('../images/clear_sky_night.png'),
  [WeatherConditions.FEW_CLOUDS_NIGHT]: require('../images/scattered_clouds.png'),
  [WeatherConditions.SCATTERED_CLOUDS_NIGHT]: require('../images/scattered_clouds.png'),
  [WeatherConditions.BROKEN_CLOUDS_NIGHT]: require('../images/broken_clouds.png'),
  [WeatherConditions.SHOWER_RAIN_NIGHT]: require('../images/shower_rain.png'),
  [WeatherConditions.RAIN_NIGHT]: require('../images/rain.png'),
  [WeatherConditions.THUNDERSTORM_NIGHT]: require('../images/thunderstorm.png'),
  [WeatherConditions.SNOW_NIGHT]: require('../images/snow.png'),
  [WeatherConditions.MIST_NIGHT]: require('../images/mist.png'),
  [WeatherConditions.ERROR_CLOUD]: require('../images/error_cloud.png'),
};

export const WEATHER_COLORS: Record<WeatherConditions, [string, string]> = {
  [WeatherConditions.CLEAR_SKY_DAY]: ['#2E4799', '#7E9DF5'],
  [WeatherConditions.FEW_CLOUDS_DAY]: ['#4D5F99', '#9EAEDB'],
  [WeatherConditions.SCATTERED_CLOUDS_DAY]: ['#4D5980', '#8A92A8'],
  [WeatherConditions.BROKEN_CLOUDS_DAY]: ['#4D5980', '#8A92A8'],
  [WeatherConditions.SHOWER_RAIN_DAY]: ['#4D5980', '#8A92A8'],
  [WeatherConditions.RAIN_DAY]: ['#4D5980', '#8A92A8'],
  [WeatherConditions.THUNDERSTORM_DAY]: ['#4D5980', '#8A92A8'],
  [WeatherConditions.SNOW_DAY]: ['#4D5F99', '#9EAEDB'],
  [WeatherConditions.MIST_DAY]: ['#4D5F99', '#9EAEDB'],
  [WeatherConditions.CLEAR_SKY_NIGHT]: ['#0B1D3F', '#094768'],
  [WeatherConditions.FEW_CLOUDS_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.SCATTERED_CLOUDS_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.BROKEN_CLOUDS_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.SHOWER_RAIN_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.RAIN_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.THUNDERSTORM_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.SNOW_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.MIST_NIGHT]: ['#161E2E', '#335668'],
  [WeatherConditions.ERROR_CLOUD]: ['#4D5980', '#8A92A8'],
};
